# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source global definitions
[[ -f /etc/bashrc ]] && . /etc/bashrc

# Bash Settings

	#set -o nounset     # These two options are useful for debugging
	#set -o xtrace
ulimit -S -c 0
set -o notify
set -o noclobber
set -o ignoreeof
shopt -s autocd

PS1='[\u@\h \W]\$ '

# Variables declaration
export EDITOR="/usr/bin/vim"
export DOTFILES="$HOME/wrk/dot"
export GEM_HOME="$HOME/.gem"
export PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin:/home/alphaxi/.gem/ruby/2.6.0/bin"

for i in $DOTFILES/shell/profile.d/*.sh ; do
	[[ -r $i ]] && . $i
done
